services:
  gateway:
    build: ./microservices/gateway
    ports:
      - "5060:5000"
    container_name: epood-gateway
    depends_on:
      - users
      - products
      - orders

  users:
    build: ./microservices/users
    ports:
      - "5051:5001"
    container_name: epood-users

  products:
    build: ./microservices/products
    ports:
      - "5052:5002"
    container_name: epood-products

  orders:
    build: ./microservices/orders
    ports:
      - "5053:5003"
    container_name: epood-orders
    depends_on:
      - users
      - products
